# Generated by Django 5.2.7 on 2025-11-01 15:41

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('organization', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('analyst', 'Analyst'), ('viewer', 'Viewer')], default='viewer', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cdm_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('creation_date', models.DateTimeField()),
                ('originator', models.CharField(max_length=255)),
                ('message_for', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=100)),
                ('object1_name', models.CharField(max_length=255)),
                ('object1_designator', models.CharField(max_length=50)),
                ('object1_catalog_name', models.CharField(default='SATCAT', max_length=50)),
                ('object1_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('object2_name', models.CharField(max_length=255)),
                ('object2_designator', models.CharField(max_length=50)),
                ('object2_catalog_name', models.CharField(default='SATCAT', max_length=50)),
                ('object2_object_type', models.CharField(blank=True, max_length=50, null=True)),
                ('tca', models.DateTimeField(help_text='Time of Closest Approach')),
                ('miss_distance', models.FloatField(help_text='Miss distance in meters')),
                ('relative_speed', models.FloatField(help_text='Relative speed in m/s')),
                ('collision_probability', models.FloatField(help_text='Probability of collision')),
                ('collision_probability_method', models.CharField(blank=True, max_length=100, null=True)),
                ('object1_position', models.JSONField(help_text='Position vector [x, y, z] in km')),
                ('object1_velocity', models.JSONField(help_text='Velocity vector [vx, vy, vz] in km/s')),
                ('object1_covariance_matrix', models.JSONField(blank=True, null=True)),
                ('object2_position', models.JSONField(help_text='Position vector [x, y, z] in km')),
                ('object2_velocity', models.JSONField(help_text='Velocity vector [vx, vy, vz] in km/s')),
                ('object2_covariance_matrix', models.JSONField(blank=True, null=True)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('status', models.CharField(choices=[('received', 'Received'), ('analyzing', 'Analyzing'), ('analyzed', 'Analyzed'), ('maneuver_planned', 'Maneuver Planned'), ('maneuver_executed', 'Maneuver Executed'), ('passed', 'Passed'), ('false_alarm', 'False Alarm')], default='received', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdms_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdms_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CDM',
                'verbose_name_plural': 'CDMs',
                'ordering': ['-tca'],
            },
        ),
        migrations.CreateModel(
            name='CollisionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_id', models.CharField(max_length=100, unique=True)),
                ('analysis_method', models.CharField(max_length=100)),
                ('time_window_start', models.DateTimeField()),
                ('time_window_end', models.DateTimeField()),
                ('combined_risk_score', models.FloatField()),
                ('recommendation', models.TextField()),
                ('recommended_action', models.CharField(choices=[('monitor', 'Continue Monitoring'), ('maneuver', 'Execute Maneuver'), ('no_action', 'No Action Required')], max_length=50)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cdms', models.ManyToManyField(related_name='analyses', to='core.cdm')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Collision Analysis',
                'verbose_name_plural': 'Collision Analyses',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='ManeuverPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maneuver_id', models.CharField(max_length=100, unique=True)),
                ('maneuver_type', models.CharField(choices=[('in_track', 'In-Track'), ('cross_track', 'Cross-Track'), ('radial', 'Radial'), ('combined', 'Combined')], max_length=50)),
                ('delta_v', models.JSONField(help_text='Delta-V vector [x, y, z] in m/s')),
                ('maneuver_time', models.DateTimeField()),
                ('execution_duration', models.FloatField(help_text='Duration in seconds')),
                ('new_miss_distance', models.FloatField(help_text='Predicted miss distance after maneuver in meters')),
                ('new_collision_probability', models.FloatField(help_text='Predicted collision probability after maneuver')),
                ('fuel_cost', models.FloatField(blank=True, help_text='Fuel cost in kg or percent', null=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('scheduled', 'Scheduled'), ('executed', 'Executed'), ('cancelled', 'Cancelled')], default='proposed', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cdm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maneuver_plans', to='core.cdm')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
