# Generated by Django 5.2.7 on 2025-11-07 21:37

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_designator', models.CharField(max_length=32, unique=True)),
                ('object_name', models.CharField(max_length=128)),
                ('object_type', models.CharField(choices=[('PAYLOAD', 'PAYLOAD'), ('ROCKET BODY', 'ROCKET BODY'), ('DEBRIS', 'DEBRIS'), ('UNKNOWN', 'UNKNOWN'), ('OTHER', 'OTHER')], default='UNKNOWN', max_length=12)),
                ('operator_organization', models.CharField(max_length=128)),
                ('maneuverable', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='CDM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tca', models.DateTimeField()),
                ('miss_distance_m', models.FloatField(blank=True, null=True)),
                ('relative_position_r', models.FloatField(blank=True, null=True)),
                ('relative_position_t', models.FloatField(blank=True, null=True)),
                ('relative_position_n', models.FloatField(blank=True, null=True)),
                ('collision_probability', models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('collision_probability_method', models.CharField(default='OTHER', max_length=32)),
                ('obj1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdms_as_obj1', to='core.spaceobject')),
                ('obj2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdms_as_obj2', to='core.spaceobject')),
            ],
        ),
    ]
