# Generated by Django 5.2.7 on 2025-11-16 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_spaceobject_cdm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('representative_tca', models.DateTimeField()),
                ('obj1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_as_obj1', to='core.spaceobject')),
                ('obj2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_as_obj2', to='core.spaceobject')),
            ],
        ),
        migrations.AddField(
            model_name='cdm',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdms', to='core.event'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['obj1', 'obj2', 'representative_tca'], name='core_event_obj1_id_0d60ef_idx'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('obj1', 'obj2', 'representative_tca'), name='unique_event_per_conjunction'),
        ),
    ]
