# Generated by Django 5.2.7 on 2025-11-22 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_cdm_event_event_core_event_obj1_id_0d60ef_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdm',
            name='hard_body_radius',
            field=models.FloatField(blank=True, help_text='Combined hard body radius (meters)', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='cdm',
            name='obj1_covariance_matrix',
            field=models.JSONField(blank=True, help_text='Object 1 6x6 covariance matrix in ECI frame (m^2, m^2/s, nested array)', null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='obj1_position_x',
            field=models.FloatField(blank=True, help_text='Object 1 X position in ECI frame (meters)', null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='obj1_position_y',
            field=models.FloatField(blank=True, help_text='Object 1 Y position in ECI frame (meters)', null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='obj1_position_z',
            field=models.FloatField(blank=True, help_text='Object 1 Z position in ECI frame (meters)', null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='obj1_velocity_x',
            field=models.FloatField(blank=True, help_text='Object 1 X velocity in ECI frame (m/s)', null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='obj1_velocity_y',
            field=models.FloatField(blank=True, help_text='Object 1 Y velocity in ECI frame (m/s)', null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='obj1_velocity_z',
            field=models.FloatField(blank=True, help_text='Object 1 Z velocity in ECI frame (m/s)', null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='obj2_covariance_matrix',
            field=models.JSONField(blank=True, help_text='Object 2 6x6 covariance matrix in ECI frame (m^2, m^2/s, nested array)', null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='obj2_position_x',
            field=models.FloatField(blank=True, help_text='Object 2 X position in ECI frame (meters)', null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='obj2_position_y',
            field=models.FloatField(blank=True, help_text='Object 2 Y position in ECI frame (meters)', null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='obj2_position_z',
            field=models.FloatField(blank=True, help_text='Object 2 Z position in ECI frame (meters)', null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='obj2_velocity_x',
            field=models.FloatField(blank=True, help_text='Object 2 X velocity in ECI frame (m/s)', null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='obj2_velocity_y',
            field=models.FloatField(blank=True, help_text='Object 2 Y velocity in ECI frame (m/s)', null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='obj2_velocity_z',
            field=models.FloatField(blank=True, help_text='Object 2 Z velocity in ECI frame (m/s)', null=True),
        ),
    ]
