# Generated by Django 5.2.7 on 2025-11-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_cdm_event_event_core_event_obj1_id_0d60ef_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cdm',
            old_name='relative_position_n',
            new_name='relative_speed_ms',
        ),
        migrations.RemoveField(
            model_name='cdm',
            name='event',
        ),
        migrations.RemoveField(
            model_name='cdm',
            name='relative_position_r',
        ),
        migrations.RemoveField(
            model_name='cdm',
            name='relative_position_t',
        ),
        migrations.AddField(
            model_name='cdm',
            name='ccsds_version',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='cdm_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='comments',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='insert_epoch',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='message_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='originator',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='relative_position',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='relative_velocity',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spaceobject',
            name='physical_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='spaceobject',
            name='state_vector',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cdm',
            name='collision_probability',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='cdm',
            name='collision_probability_method',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='spaceobject',
            name='maneuverable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='spaceobject',
            name='object_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='spaceobject',
            name='object_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='spaceobject',
            name='operator_organization',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
