# Generated by Django 5.2.7 on 2025-11-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_relative_position_n_cdm_relative_speed_ms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spaceobject',
            name='physical_parameters',
        ),
        migrations.RemoveField(
            model_name='spaceobject',
            name='state_vector',
        ),
        migrations.AddField(
            model_name='cdm',
            name='physical_parameters_obj1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='physical_parameters_obj2',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='state_vector_obj1',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='state_vector_obj2',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
