# Generated by Django 5.2.7 on 2026-01-16 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cdm_hard_body_radius_cdm_obj1_covariance_matrix_and_more'),
        ('core', '0005_remove_spaceobject_physical_parameters_and_more'),
    ]

    operations = [
    ]
