# Generated by Django 5.2.7 on 2026-01-16 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_merge_20260116_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdm',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdms', to='core.event'),
        ),
    ]
