# Generated by Django 5.2.7 on 2026-01-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cdm_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdm',
            name='collision_probability',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
    ]
