# Generated by Django 5.2.7 on 2026-01-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cdm_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdm',
            name='comment_emergency_reportable',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='constellation',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='filename',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='message_for',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
