# Generated by Django 5.2.7 on 2026-03-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_cdm_collision_probability'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('worker', 'Worker'), ('observer', 'Observer')], default='observer', help_text='User role determining access permissions', max_length=20),
        ),
    ]
