# Generated by Django 5.2.7 on 2026-01-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cdm_comment_emergency_reportable_cdm_constellation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdm',
            name='extra',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='spaceobject',
            name='international_designator',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
