# Generated by Django 5.2.7 on 2026-04-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='cdm',
            name='collision_probability_alfano',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='collision_probability_monte_carlo',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='cdm',
            name='collision_probability_multistep',
            field=models.DecimalField(blank=True, decimal_places=100, max_digits=100, null=True),
        ),
    ]
